name: Deploy to Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: 611a2000-d9df-41af-9c57-882edefadcc4
          tenant-id: e4a6a357-5564-4e75-a12f-65b55d95db83
          subscription-id: 1cdefba8-8b5b-44dd-8a6e-46f5b4005027

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.3.1

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan   # 👈 ye batata hai Apply stage sirf Plan ke baad chale
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: 611a2000-d9df-41af-9c57-882edefadcc4
          tenant-id: e4a6a357-5564-4e75-a12f-65b55d95db83
          subscription-id: 1cdefba8-8b5b-44dd-8a6e-46f5b4005027

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.3.1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve -no-color -input=false
