name: Terraform Pipeline

on:
  push:
    branches:
      - main    # sirf main branch pe

jobs:
  terraform:
    runs-on: myagentongit   # yeh tumhara self-hosted runner hai

    steps:
      

      # Step 2: Terraform init
      - name: Terraform Init
        run: terraform init

      # Step 3: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
