name: Deploy to Azure

on: workflow_dispatch
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
         clientId: c1e88437-228e-4781-8d87-91802824c7e2
         tenantId: ebf03ffb-2313-48d8-80e9-670bbb83e7d9
         subscriptionId: c751b003-03b2-41f7-8579-5c1a60f11ac2
         enable-AzPSSession: false
         environment: azurecloud
         allow-no-subscriptions: false
         audience: api://AzureADTokenExchange
         auth-type: SERVICE_PRINCIPAL


      - name: Terraform Init
        run: terraform init



            
    

      - name: Terraform Plan
        run: terraform plan -out=tfplan

     
