name: Deploy to Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: c1e88437-228e-4781-8d87-91802824c7e2
          tenant-id: ebf03ffb-2313-48d8-80e9-670bbb83e7d9
          subscription-id: c751b003-03b2-41f7-8579-5c1a60f11ac2
