name: Hello Printer

on:
  push:            # jab bhi repo me push hoga
  workflow_dispatch:  # manually bhi chala sakte ho

jobs:
  say-hello:
    runs-on: myagentongit
    steps:
      - name: Print message
        run: echo "hello printer"
